sudo: required 

services:
  - docker

before_install:
  - docker build -t abhyudaya/docker-react -f Dockerfile.dev .

script:
  - docker run abhyudaya/docker-react npm run test -- --coverage 
# -- -- coverage to exit the test case when finished
